/**
 * Privacy Policy content, mirrored verbatim from the iOS app's
 * Localizable.strings (legal.privacy.section*) — Apple reviewer compares
 * the in-app text against the web Privacy URL, so these must match.
 *
 * EN and TR are the canonical translations. ES and AR fall back to EN
 * for v1.0 (translation pending — see TODO).
 */

import { type Locale } from "@/i18n/routing";

export type PrivacySection = { title: string; body: string };

export interface PrivacyContent {
  brand: string;            // eyebrow
  title: string;            // h1
  lastUpdated: string;      // sub-h1
  sections: PrivacySection[];
}

const EN: PrivacyContent = {
  brand: "WeSafe",
  title: "Privacy Policy",
  lastUpdated: "Last updated: May 2026",
  sections: [
    {
      title: "1. Data Controller and Applicable Law",
      body:
        "WeSafe (the “Service”, “we”, “us”, or “our”) acts as the controller of the personal data you provide through the Service. We process your data in accordance with the data-protection law applicable in your jurisdiction, including:\n\n" +
        "- **KVKK** (Law No. 6698) — for users in Türkiye\n" +
        "- **GDPR** (Regulation 2016/679) — for users in the EU/EEA\n" +
        "- **UK GDPR & DPA 2018** — for users in the United Kingdom\n" +
        "- **CCPA/CPRA** — for residents of California, USA\n" +
        "- **LGPD** (Law No. 13.709) — for users in Brazil\n" +
        "- **PIPEDA** — for users in Canada\n" +
        "- Other applicable local data-protection regulations\n\n" +
        "Wherever you are, your data is processed under the principles of lawfulness, transparency, purpose limitation, data minimisation, and good faith.",
    },
    {
      title: "2. Personal Data Collected",
      body:
        "The Service collects the following personal data:\n\n" +
        "- **Account Information**: First name, last name, email address\n" +
        "- **Contact Information**: Mobile phone number, your designated emergency contacts\n" +
        "- **Location Data**: Real-time location during SOS, check-in, and location-sharing features\n" +
        "- **Audio / Visual Data**: Camera and microphone access during an active SOS (with your explicit consent)\n" +
        "- **User Identifier**: Anonymous user ID generated by Firebase Authentication\n\n" +
        "We do not collect any government-issued identification number, date of birth, passport, national ID, or other identity-document data. This data is processed solely on the basis of your explicit consent and/or legitimate-interest grounds under the data-protection law applicable to you.",
    },
    {
      title: "3. Purposes of Data Processing",
      body:
        "Your personal data is processed for the following purposes:\n\n" +
        "- Creating and transmitting emergency notifications\n" +
        "- Sharing your location with your designated emergency contacts\n" +
        "- Providing safe arrival tracking through the check-in feature\n" +
        "- Creating community safety reports\n" +
        "- Volunteer coordination and routing\n" +
        "- Maintaining and improving application functionality",
    },
    {
      title: "4. Data Transfers",
      body:
        "Your personal data is processed on Google Firebase servers hosted in the EU (eur3 multi-region: Belgium and the Netherlands). When data is necessarily transferred across regions for technical operations:\n\n" +
        "- **EU/EEA users (GDPR)**: transfers rely on Google's Standard Contractual Clauses (SCCs) approved by the European Commission under GDPR Art. 46.\n" +
        "- **Türkiye users (KVKK)**: cross-border transfers rely on your explicit consent (Art. 9) and the technical safeguards described in Section 5.\n" +
        "- **UK users (UK GDPR)**: transfers comply with the UK International Data Transfer Agreement (IDTA).\n" +
        "- **California users (CCPA/CPRA)**: we do not sell or share your personal information.\n\n" +
        "Your data is never shared with third parties for advertising, marketing, or any commercial purpose other than the safety service. Data may be disclosed to competent public authorities only when legally required in your jurisdiction.",
    },
    {
      title: "5. Data Security",
      body:
        "The following technical and administrative measures are implemented to protect your personal data:\n\n" +
        "- Data is transmitted and stored encrypted (TLS/SSL) on Firebase infrastructure\n" +
        "- Identity verification is secured through Firebase Authentication\n" +
        "- Authorization controls are enforced through Firestore security rules\n" +
        "- Sensitive in-app data is stored encrypted on the device\n" +
        "- Location data is collected only when the relevant feature is active",
    },
    {
      title: "6. Your Rights",
      body:
        "Regardless of which law applies to you, WeSafe extends the following core rights to every user:\n\n" +
        "- **Right of access** — request a copy of the data we hold about you\n" +
        "- **Right to rectification** — correct inaccurate or incomplete data\n" +
        "- **Right to erasure** — delete your account and associated data\n" +
        "- **Right to restriction** — limit how we process your data\n" +
        "- **Right to data portability** — receive your data in a machine-readable format\n" +
        "- **Right to object** — to processing based on legitimate interest\n" +
        "- **Right not to be subject to automated decision-making**\n\n" +
        "### Region-specific rights\n\n" +
        "- **EU/EEA (GDPR)**: right to lodge a complaint with your national supervisory authority\n" +
        "- **Türkiye (KVKK Art. 11)**: the rights above as enumerated in KVKK\n" +
        "- **California (CCPA/CPRA)**: right to know, delete, correct, opt out of sale/sharing (we do neither), and limit use of sensitive personal information\n" +
        "- **United Kingdom (UK GDPR)**: same rights as EU/EEA; complaints to the ICO\n" +
        "- **Brazil (LGPD)**: confirmation, access, correction, anonymisation, portability, deletion, and revocation of consent\n" +
        "- **Canada (PIPEDA)**: access and challenge accuracy\n\n" +
        "To exercise any right contact **privacy@we-safe.io**. We respond within the timeframe required by your applicable law (e.g. 30 days under GDPR; 45 days under CCPA).",
    },
    {
      title: "7. Cookies and Tracking Technologies",
      body:
        "WeSafe does not use any advertising tracking technologies or third-party analytics tools. Only UserDefaults (local on-device storage) required for the basic functionality of the application is used.",
    },
    {
      title: "8. Policy Changes and Contact",
      body:
        "This Privacy Policy may be updated. Significant changes will be announced through in-app notifications. The current version of the policy is always accessible from within the application.\n\n" +
        "For all privacy-related questions, requests, and inquiries: **privacy@we-safe.io**",
    },
  ],
};

const TR: PrivacyContent = {
  brand: "WeSafe",
  title: "Gizlilik Politikası",
  lastUpdated: "Son güncelleme: Mayıs 2026",
  sections: [
    {
      title: "1. Veri Sorumlusu ve Uygulanan Hukuk",
      body:
        "WeSafe (“Hizmet”), kişisel verilerinizin veri sorumlusudur. Verileriniz, bulunduğunuz ülkedeki veri koruma mevzuatına uygun olarak işlenir:\n\n" +
        "- **KVKK** (6698 sayılı Kanun) — Türkiye'deki kullanıcılar için\n" +
        "- **GDPR** (2016/679 sayılı Tüzük) — AB/AEA'daki kullanıcılar için\n" +
        "- **UK GDPR & DPA 2018** — Birleşik Krallık'taki kullanıcılar için\n" +
        "- **CCPA/CPRA** — Kaliforniya, ABD sakinleri için\n" +
        "- **LGPD** (13.709 sayılı Kanun) — Brezilya'daki kullanıcılar için\n" +
        "- **PIPEDA** — Kanada'daki kullanıcılar için\n" +
        "- Diğer geçerli yerel veri koruma düzenlemeleri\n\n" +
        "Bulunduğunuz yerden bağımsız olarak verileriniz hukuka uygunluk, şeffaflık, amaçla sınırlılık, veri minimizasyonu ve dürüstlük ilkelerine göre işlenir.",
    },
    {
      title: "2. Toplanan Kişisel Veriler",
      body:
        "Hizmet aşağıdaki kişisel verileri toplar:\n\n" +
        "- **Hesap Bilgileri**: Ad, soyad, e-posta adresi\n" +
        "- **İletişim Bilgileri**: Cep telefonu numarası, belirlediğiniz acil durum kişileri\n" +
        "- **Konum Verisi**: SOS, check-in ve konum paylaşımı özelliklerinde anlık konum bilgisi\n" +
        "- **Görsel / İşitsel Veriler**: Aktif SOS sırasında kamera ve mikrofon erişimi (açık rızanızla)\n" +
        "- **Kullanıcı Tanımlayıcısı**: Firebase Authentication tarafından oluşturulan anonim kullanıcı kimliği\n\n" +
        "T.C. Kimlik Numarası, doğum tarihi, pasaport, ulusal kimlik kartı veya başka herhangi bir resmi kimlik belgesi verisi toplanmaz. Bu veriler yalnızca açık rızanıza ve/veya size uygulanabilir veri koruma mevzuatı kapsamındaki meşru menfaat hukuki sebeplerine dayanılarak işlenir.",
    },
    {
      title: "3. Veri İşleme Amaçları",
      body:
        "Kişisel verileriniz aşağıdaki amaçlarla işlenir:\n\n" +
        "- Acil durum bildirimlerinin oluşturulması ve iletilmesi\n" +
        "- Konumunuzun belirlediğiniz acil durum kişileriyle paylaşılması\n" +
        "- Check-in özelliği ile güvenli varış takibinin sağlanması\n" +
        "- Topluluk güvenlik raporlarının oluşturulması\n" +
        "- Gönüllü koordinasyonu ve yönlendirilmesi\n" +
        "- Uygulama işlevselliğinin sürdürülmesi ve iyileştirilmesi",
    },
    {
      title: "4. Veri Aktarımı",
      body:
        "Kişisel verileriniz, AB'de barındırılan (eur3 çok bölgeli: Belçika ve Hollanda) Google Firebase sunucularında işlenir. Teknik operasyonlar için bölgeler arası veri aktarımı zorunlu olduğunda:\n\n" +
        "- **AB/AEA kullanıcıları (GDPR)**: aktarımlar, GDPR Md. 46 kapsamında Avrupa Komisyonu tarafından onaylanan Standart Sözleşme Maddeleri'ne (SCC) dayanır.\n" +
        "- **Türkiye kullanıcıları (KVKK)**: yurt dışı aktarımları açık rızanıza (Md. 9) ve 5. Bölümde açıklanan teknik önlemlere dayanır.\n" +
        "- **BK kullanıcıları (UK GDPR)**: aktarımlar UK International Data Transfer Agreement (IDTA) ile uyumludur.\n" +
        "- **Kaliforniya kullanıcıları (CCPA/CPRA)**: kişisel bilgilerinizi satmıyor veya paylaşmıyoruz.\n\n" +
        "Verileriniz, güvenlik hizmeti dışında reklam, pazarlama veya başka herhangi bir ticari amaç için üçüncü taraflarla asla paylaşılmaz. Veriler, yalnızca bulunduğunuz ülkede yasal olarak gerekli olduğunda yetkili kamu makamlarına açıklanabilir.",
    },
    {
      title: "5. Veri Güvenliği",
      body:
        "Kişisel verilerinizi korumak için aşağıdaki teknik ve idari önlemler uygulanır:\n\n" +
        "- Veriler, Firebase altyapısında şifrelenmiş olarak (TLS/SSL) iletilir ve saklanır\n" +
        "- Kimlik doğrulama Firebase Authentication ile güvence altına alınır\n" +
        "- Yetkilendirme denetimleri Firestore güvenlik kuralları ile uygulanır\n" +
        "- Uygulama içi hassas veriler cihazda şifreli olarak saklanır\n" +
        "- Konum verisi yalnızca ilgili özellik aktifken toplanır",
    },
    {
      title: "6. Haklarınız",
      body:
        "Hangi hukuk size uygulanırsa uygulansın, WeSafe her kullanıcıya aşağıdaki temel hakları tanır:\n\n" +
        "- **Erişim hakkı** — hakkınızda tuttuğumuz verilerin bir kopyasını talep etme\n" +
        "- **Düzeltme hakkı** — yanlış veya eksik verileri düzeltme\n" +
        "- **Silme hakkı** — hesabınızı ve ilişkili verilerinizi silme\n" +
        "- **İşlemeyi kısıtlama hakkı** — verilerinizi nasıl işlediğimizi sınırlama\n" +
        "- **Veri taşınabilirliği hakkı** — verilerinizi makine tarafından okunabilir bir biçimde alma\n" +
        "- **İtiraz hakkı** — meşru menfaate dayalı işlemeye itiraz\n" +
        "- **Otomatik karar alma süreçlerine tabi olmama hakkı**\n\n" +
        "### Bölgeye özel haklar\n\n" +
        "- **AB/AEA (GDPR)**: ulusal denetim otoritenize şikayette bulunma hakkı\n" +
        "- **Türkiye (KVKK Md. 11)**: KVKK'da sayılan yukarıdaki haklar\n" +
        "- **Kaliforniya (CCPA/CPRA)**: bilme, silme, düzeltme, satış/paylaşımı reddetme (biz zaten yapmıyoruz) ve hassas kişisel bilgilerin kullanımını sınırlama hakkı\n" +
        "- **Birleşik Krallık (UK GDPR)**: AB/AEA ile aynı haklar; şikayetler ICO'ya yapılır\n" +
        "- **Brezilya (LGPD)**: teyit, erişim, düzeltme, anonimleştirme, taşınabilirlik, silme ve rızanın geri alınması\n" +
        "- **Kanada (PIPEDA)**: erişim ve doğruluğa itiraz hakkı\n\n" +
        "Herhangi bir hakkı kullanmak için **privacy@we-safe.io** adresinden bize ulaşın. Size uygulanabilir hukukun gerektirdiği süre içinde yanıt veririz (örn. GDPR kapsamında 30 gün; CCPA kapsamında 45 gün).",
    },
    {
      title: "7. Çerezler ve İzleme Teknolojileri",
      body:
        "WeSafe herhangi bir reklam izleme teknolojisi veya üçüncü taraf analiz aracı kullanmaz. Yalnızca uygulamanın temel işlevselliği için gereken UserDefaults (cihaz üzerinde yerel depolama) kullanılır.",
    },
    {
      title: "8. Politika Değişiklikleri ve İletişim",
      body:
        "İşbu Gizlilik Politikası güncellenebilir. Önemli değişiklikler uygulama içi bildirimlerle duyurulur. Politikanın güncel sürümüne her zaman uygulama içinden erişilebilir.\n\n" +
        "Gizlilikle ilgili tüm sorular, talepler ve başvurular için: **privacy@we-safe.io**",
    },
  ],
};

// Spanish and Arabic fall back to English for v1.0.
const ES: PrivacyContent = EN;
const AR: PrivacyContent = EN;

const MAP: Record<Locale, PrivacyContent> = { en: EN, tr: TR, es: ES, ar: AR };

export function getPrivacyContent(locale: Locale): PrivacyContent {
  return MAP[locale] ?? EN;
}
